package main

var Captains map[string]int = map[string]int{
	"trfvirsh":       1,
	"sabnc":          1,
	"blakavenge":     1,
	"lordofmanatees": 1,
	"mtndewm3":       1,
	"phdzivanovich":  1,
	"ozymandias23":   1,
	"stoicheion":     1,
	"presidentnixon": 1,
	"beardeddog":     1,
	"jlysinger":      1,
	"docm":           1,
	"changster32":    1,
	"lovestories":    1,
	"fac3tofloor":    1,
	"vahti":          1,
	"twidgeegh":      1,
	"cheagasus":      1,
	"filthypeasants": 1,
	"silentk":        1,
	"darandin":       1,
	"zelchor":        1,
	"ddm13":          1,
	"mullney":        1,
}
